apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-config
  namespace: threat-hunting
data:
  config.yml: |
    aws:
      access_key: "YOUR_AWS_ACCESS_KEY_ID"
      secret_key: "YOUR_AWS_SECRET_ACCESS_KEY"
      region: "us-east-1"
    restrictive_security_group_id: "sg-0a1b2c3d4e5f6g7h"
    firewall:
      api_url: "https://firewall-api.example.com"
      api_key: "YOUR_FIREWALL_API_KEY"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: threat-hunting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: yourregistry/threat-orchestrator:latest
        imagePullPolicy: IfNotPresent
        command: ["python3", "-u", "/app/orchestrator/runner.py"]
        volumeMounts:
        - name: config
          mountPath: /app/orchestrator/playbooks/config.yml
          subPath: config.yml
        - name: code
          mountPath: /app/orchestrator
      volumes:
      - name: config
        configMap:
          name: orchestrator-config
      - name: code
        hostPath:
          path: /opt/threat-hunting-platform/orchestrator
          type: Directory

